name: auth_todo_flutter
description: A new Flutter project with Serverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.10
  logger: ^2.0.2+1
  go_router: ^13.2.0

  cupertino_icons: ^1.0.5

  serverpod_flutter: 1.2.3
  auth_todo_client:
    path: ../auth_todo_client

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
